# Data Understanding

# Import Libraries

In [7]:
import pandas as pd
import numpy as np

## Define Data Sources

### Load Dataset

In [ ]:
import pandas as pd

file_path = "../data/raw/2025_lar.csv"
sample_size = 1000000

df = pd.read_csv(file_path, nrows=sample_size, na_values=['', 'Exempt', 'NA', 'na'])

print(f"Loaded DataFrame: {df.shape[0]} rows, {df.shape[1]} columns.")

/var/folders/y7/26jshzmn0g173gpd4sbpsk0m0000gp/T/ipykernel_11029/4181930206.py:6: DtypeWarning: Columns (43: total_units) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, nrows=sample_size, na_values=['', 'Exempt', 'NA', 'na', 'Exempt/NA'])

Loaded DataFrame: 1000000 rows, 99 columns.

### Memory Optimization

In [9]:
# Calculate initial memory in MB
initial_memory = df.memory_usage(deep=True).sum() / (1024**2)

# Convert string/object columns to category
object_cols = df.select_dtypes(include='object').columns
df[object_cols] = df[object_cols].astype('category')

# Downcast 64-bit floats to 32-bit
float_cols = df.select_dtypes(include='float64').columns
df[float_cols] = df[float_cols].astype('float32')

# Downcast 64-bit integers to 32-bit
int_cols = df.select_dtypes(include='int64').columns
df[int_cols] = df[int_cols].astype('int32')

# Calculate final memory in MB
final_memory = df.memory_usage(deep=True).sum() / (1024**2)
reduction = (1 - final_memory / initial_memory) * 100

print(f"Memory Usage: Reduced from {initial_memory:.2f} MB to {final_memory:.2f} MB ({reduction:.1f}% reduction)")

/var/folders/y7/26jshzmn0g173gpd4sbpsk0m0000gp/T/ipykernel_11029/39469949.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include='object').columns

Memory Usage: Reduced from 1411.93 MB to 338.64 MB (76.0% reduction)

## Data Description

### Dataset Information

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 99 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   activity_year                             1000000 non-null  int32
 1   lei                                       1000000 non-null  category
 2   derived_msa_md                            1000000 non-null  int32
 3   state_code                                975764 non-null   category
 4   county_code                               961207 non-null   float32
 5   census_tract                              960856 non-null   float32
 6   conforming_loan_limit                     993013 non-null   category
 7   derived_loan_product_type                 1000000 non-null  category
 8   derived_dwelling_category                 1000000 non-null  category
 9   derived_ethnicity                         1000000 non-null  category
 10  derived_race                              1000000 non-null  category
 11  derived_sex                               1000000 non-null  category
 12  action_taken                              1000000 non-null  int32
 13  purchaser_type                            1000000 non-null  int32
 14  preapproval                               1000000 non-null  int32
 15  loan_type                                 1000000 non-null  int32
 16  loan_purpose                              1000000 non-null  int32
 17  lien_status                               1000000 non-null  int32
 18  reverse_mortgage                          1000000 non-null  int32
 19  open_end_line_of_credit                   1000000 non-null  int32
 20  business_or_commercial_purpose            1000000 non-null  int32
 21  loan_amount                               1000000 non-null  int32
 22  combined_loan_to_value_ratio              736682 non-null   float32
 23  interest_rate                             596508 non-null   float32
 24  rate_spread                               515144 non-null   float32
 25  hoepa_status                              1000000 non-null  int32
 26  total_loan_costs                          416683 non-null   float32
 27  total_points_and_fees                     6531 non-null     float32
 28  origination_charges                       425536 non-null   float32
 29  discount_points                           180911 non-null   float32
 30  lender_credits                            117696 non-null   float32
 31  loan_term                                 897745 non-null   float32
 32  prepayment_penalty_term                   13734 non-null    float32
 33  intro_rate_period                         144678 non-null   float32
 34  negative_amortization                     1000000 non-null  int32
 35  interest_only_payment                     1000000 non-null  int32
 36  balloon_payment                           1000000 non-null  int32
 37  other_nonamortizing_features              1000000 non-null  int32
 38  property_value                            753426 non-null   float32
 39  construction_method                       1000000 non-null  int32
 40  occupancy_type                            1000000 non-null  int32
 41  manufactured_home_secured_property_type   1000000 non-null  int32
 42  manufactured_home_land_property_interest  1000000 non-null  int32
 43  total_units                               1000000 non-null  category
 44  multifamily_affordable_units              4172 non-null     float32
 45  income                                    949264 non-null   float32
 46  debt_to_income_ratio                      719564 non-null   category
 47  applicant_credit_score_type               1000000 non-null  int32
 48  co_applicant_credit_score_type            1000000 non-null  int32
 49  applicant_ethnicity_1                     999902 non-null   float32
 50  applicant_ethnicity_2                     62437 non-null    float32
 51  applicant_ethnicity_3                     1173 non-null     float32
 52  applicant_ethnicity_4                     43 non-null       float32
 53  applicant_ethnicity_5                     17 non-null       float32
 54  co_applicant_ethnicity_1                  999970 non-null   float32
 55  co_applicant_ethnicity_2                  23863 non-null    float32
 56  co_applicant_ethnicity_3                  400 non-null      float32
 57  co_applicant_ethnicity_4                  17 non-null       float32
 58  co_applicant_ethnicity_5                  6 non-null        float32
 59  applicant_ethnicity_observed              1000000 non-null  int32
 60  co_applicant_ethnicity_observed           1000000 non-null  int32
 61  applicant_race_1                          999942 non-null   float32
 62  applicant_race_2                          48238 non-null    float32
 63  applicant_race_3                          3899 non-null     float32
 64  applicant_race_4                          629 non-null      float32
 65  applicant_race_5                          288 non-null      float32
 66  co_applicant_race_1                       999974 non-null   float32
 67  co_applicant_race_2                       19064 non-null    float32
 68  co_applicant_race_3                       1509 non-null     float32
 69  co_applicant_race_4                       251 non-null      float32
 70  co_applicant_race_5                       152 non-null      float32
 71  applicant_race_observed                   1000000 non-null  int32
 72  co_applicant_race_observed                1000000 non-null  int32
 73  applicant_sex                             1000000 non-null  int32
 74  co_applicant_sex                          1000000 non-null  int32
 75  applicant_sex_observed                    1000000 non-null  int32
 76  co_applicant_sex_observed                 1000000 non-null  int32
 77  applicant_age                             1000000 non-null  category
 78  co_applicant_age                          1000000 non-null  category
 79  applicant_age_above_62                    968255 non-null   category
 80  co_applicant_age_above_62                 415082 non-null   category
 81  submission_of_application                 1000000 non-null  int32
 82  initially_payable_to_institution          1000000 non-null  int32
 83  aus_1                                     1000000 non-null  int32
 84  aus_2                                     25369 non-null    float32
 85  aus_3                                     13026 non-null    float32
 86  aus_4                                     11776 non-null    float32
 87  aus_5                                     10204 non-null    float32
 88  denial_reason_1                           1000000 non-null  int32
 89  denial_reason_2                           33032 non-null    float32
 90  denial_reason_3                           4735 non-null     float32
 91  denial_reason_4                           424 non-null      float32
 92  tract_population                          1000000 non-null  int32
 93  tract_minority_population_percent         1000000 non-null  float32
 94  ffiec_msa_md_median_family_income         1000000 non-null  int32
 95  tract_to_msa_income_percentage            1000000 non-null  float32
 96  tract_owner_occupied_units                1000000 non-null  int32
 97  tract_one_to_four_family_homes            1000000 non-null  int32
 98  tract_median_age_of_housing_units         1000000 non-null  int32
dtypes: category(14), float32(45), int32(40)
memory usage: 338.6 MB

### Data Descriptions

#### Describe Objects and Categorical Features

In [14]:
df.describe(include=['object', 'category'])

,lei,state_code,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,total_units,debt_to_income_ratio,applicant_age,co_applicant_age,applicant_age_above_62,co_applicant_age_above_62
count,1000000,975764,993013,1000000,1000000,1000000,1000000,1000000,1000000,719564,1000000,1000000,968255,415082
unique,1212,54,3,8,4,5,9,4,13,19,8,9,2,2
top,549300H3IZO24NSOO931,TX,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,1,20%-<30%,35-44,9999,No,No
freq,77468,97800,974202,537026,944334,680206,659754,354927,668708,106638,238578,567048,799163,341087

In [16]:
object_cols = df.select_dtypes(include=['object', 'category']).columns

for col in object_cols:
    print(f"\n----- {col} -----")
    print(df[col].value_counts().head(20))

----- lei -----
lei
549300H3IZO24NSOO931    77468
X05BVSK68TQ7YTOSNR22    68974
549300RPOGWJRH63HS39    51588
549300ALNLUNS3Y53T24    30019
549300Q3ROEQU3D1IW91    24749
5493006S869XKIESMV41    21713
549300LXKO1O7CSK5J52    19426
549300SK2GVCQXPD4S58    16967
54930049L5WINET09Q97    16127
5493003V40VGM7YDFM54    15377
54930063XGNMIXS57091    12943
254900CN1DD55MJDFH69    12022
549300Q50XCC0473FG63    10915
549300ZZME37MXI1EF14    10697
549300VQUTI5IU7GXT57     9801
549300KHXD7JSQUZIJ22     9523
549300ZPSJZO10ZAX556     9421
549300EM8ID8J7F8OM55     9121
549300VJQJVZKJBDWS17     9115
549300LG07PXWSIMC813     7243
Name: count, dtype: int64

----- state_code -----
state_code
TX    97800
CA    74475
FL    66471
MI    46087
PA    37343
WI    36927
UT    35555
NC    33084
IL    32127
MO    30062
NJ    29291
OH    28180
MN    26517
NY    25671
GA    24565
VA    24544
TN    23837
IN    22164
AZ    22083
CO    20049
Name: count, dtype: int64

----- conforming_loan_limit -----
conforming_loan_limit
C     974202
NC     17768
U       1043
Name: count, dtype: int64

----- derived_loan_product_type -----
derived_loan_product_type
Conventional:First Lien          537026
Conventional:Subordinate Lien    261770
FHA:First Lien                   146504
VA:First Lien                     45593
FSA/RHS:First Lien                 8620
FHA:Subordinate Lien                298
FSA/RHS:Subordinate Lien            185
VA:Subordinate Lien                   4
Name: count, dtype: int64

----- derived_dwelling_category -----
derived_dwelling_category
Single Family (1-4 Units):Site-Built      944334
Single Family (1-4 Units):Manufactured     48679
Multifamily:Site-Built                      6789
Multifamily:Manufactured                     198
Name: count, dtype: int64

----- derived_ethnicity -----
derived_ethnicity
Not Hispanic or Latino     680206
Ethnicity Not Available    169153
Hispanic or Latino         123761
Joint                       26782
Free Form Text Only            98
Name: count, dtype: int64

----- derived_race -----
derived_race
White                                        659754
Race Not Available                           177729
Black or African American                     70853
Asian                                         55634
Joint                                         21778
American Indian or Alaska Native               9184
2 or more minority races                       2544
Native Hawaiian or Other Pacific Islander      2466
Free Form Text Only                              58
Name: count, dtype: int64

----- derived_sex -----
derived_sex
Joint                354927
Male                 329660
Female               220542
Sex Not Available     94871
Name: count, dtype: int64

----- total_units -----
total_units
1          668708
1          300261
2           14453
5-24         3932
3            3389
4            2783
2            2611
>149          953
50-99         860
25-49         821
3             452
100-149       421
4             356
Name: count, dtype: int64

----- debt_to_income_ratio -----
debt_to_income_ratio
20%-<30%    106638
30%-<36%    104780
50%-60%      72345
>60%         53914
<20%         49124
49           29210
42           28376
44           28054
41           25235
43           24842
40           24346
39           23530
38           22266
48           21735
37           21581
45           21518
46           21082
47           20820
36           20168
Name: count, dtype: int64

----- applicant_age -----
applicant_age
35-44    238578
25-34    203797
45-54    201080
55-64    156618
65-74     90563
<25       40461
>74       37158
8888      31745
Name: count, dtype: int64

----- co_applicant_age -----
co_applicant_age
9999     567048
35-44     99107
25-34     93283
45-54     82394
55-64     66468
65-74     41015
<25       17990
8888      17870
>74       14825
Name: count, dtype: int64

----- applicant_age_above_62 -----
applicant_age_above_62
No     799163
Yes    169092
Name: count, dtype: int64

----- co_applicant_age_above_62 -----
co_applicant_age_above_62
No     341087
Yes     73995
Name: count, dtype: int64

#### Describe Numerical Features

In [15]:
df.describe(include=['int32', 'float32'])

,activity_year,derived_msa_md,county_code,census_tract,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,...,denial_reason_2,denial_reason_3,denial_reason_4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
count,1000000.0,1000000.000000,961207.000000,9.608560e+05,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,33032.000000,4735.000000,424.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2025.0,42315.617087,30068.511719,3.006073e+10,2.115564,10.517931,1.957379,1.264411,9.289002,1.262257,...,4.404819,5.705596,6.485849,4658.068054,33.203560,101908.086100,104.866959,1192.531972,1607.666351,34.633548
std,0.0,28243.013812,16401.212891,1.639684e+10,1.554597,24.111985,0.202001,0.581827,13.101363,0.439862,...,2.753267,2.711194,2.302181,2415.340784,25.747366,29202.034406,42.577721,611.558121,737.665433,18.863575
min,2025.0,10180.000000,1001.000000,1.001020e+09,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,2025.0,23104.000000,13295.000000,1.329502e+10,1.000000,0.000000,2.000000,1.000000,1.000000,1.000000,...,3.000000,4.000000,4.000000,3283.000000,13.000000,89300.000000,82.000000,797.000000,1166.000000,21.000000
50%,2025.0,35300.000000,30095.000000,3.009597e+10,1.000000,0.000000,2.000000,1.000000,1.000000,1.000000,...,4.000000,6.000000,7.000000,4436.000000,25.570000,103000.000000,103.000000,1153.000000,1587.000000,35.000000
75%,2025.0,45294.000000,47013.000000,4.701101e+10,3.000000,3.000000,2.000000,1.000000,31.000000,2.000000,...,6.000000,9.000000,9.000000,5777.000000,47.880001,117300.000000,127.000000,1543.000000,2031.000000,47.000000
max,2025.0,99999.000000,78030.000000,7.803096e+10,8.000000,72.000000,2.000000,4.000000,32.000000,2.000000,...,9.000000,9.000000,9.000000,30199.000000,100.000000,192300.000000,516.000000,6276.000000,8233.000000,80.000000

## Data Quality Verification

In [24]:
total_rows = len(df)
duplicate = df.duplicated().sum()
is_na = df.isna().sum()

print(f"Total Duplicates: {duplicate} out of {total_rows}\n")

for col, count in is_na.items():
    if count > 0:
        print(f"Total Missing For {col}: {count}")

Total Duplicates: 1937 out of 1000000

Total Missing For state_code: 24236
Total Missing For county_code: 38793
Total Missing For census_tract: 39144
Total Missing For conforming_loan_limit: 6987
Total Missing For combined_loan_to_value_ratio: 263318
Total Missing For interest_rate: 403492
Total Missing For rate_spread: 484856
Total Missing For total_loan_costs: 583317
Total Missing For total_points_and_fees: 993469
Total Missing For origination_charges: 574464
Total Missing For discount_points: 819089
Total Missing For lender_credits: 882304
Total Missing For loan_term: 102255
Total Missing For prepayment_penalty_term: 986266
Total Missing For intro_rate_period: 855322
Total Missing For property_value: 246574
Total Missing For multifamily_affordable_units: 995828
Total Missing For income: 50736
Total Missing For debt_to_income_ratio: 280436
Total Missing For applicant_ethnicity_1: 98
Total Missing For applicant_ethnicity_2: 937563
Total Missing For applicant_ethnicity_3: 998827
Total Missing For applicant_ethnicity_4: 999957
Total Missing For applicant_ethnicity_5: 999983
Total Missing For co_applicant_ethnicity_1: 30
Total Missing For co_applicant_ethnicity_2: 976137
Total Missing For co_applicant_ethnicity_3: 999600
Total Missing For co_applicant_ethnicity_4: 999983
Total Missing For co_applicant_ethnicity_5: 999994
Total Missing For applicant_race_1: 58
Total Missing For applicant_race_2: 951762
Total Missing For applicant_race_3: 996101
Total Missing For applicant_race_4: 999371
Total Missing For applicant_race_5: 999712
Total Missing For co_applicant_race_1: 26
Total Missing For co_applicant_race_2: 980936
Total Missing For co_applicant_race_3: 998491
Total Missing For co_applicant_race_4: 999749
Total Missing For co_applicant_race_5: 999848
Total Missing For applicant_age_above_62: 31745
Total Missing For co_applicant_age_above_62: 584918
Total Missing For aus_2: 974631
Total Missing For aus_3: 986974
Total Missing For aus_4: 988224
Total Missing For aus_5: 989796
Total Missing For denial_reason_2: 966968
Total Missing For denial_reason_3: 995265
Total Missing For denial_reason_4: 999576